export const content = {
  stats: {
    applescotti: [
      "<div class='content-item'>Clones received = _/_/2024</div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'>Plants cut down and hung = _/_/2025</div>",
      "<div class='content-item'>Plants first trim = _/_/2025</div>",
      "<div class='content-item'>Plants cured = _/_/2025</div>",
      "<div class='content-item'>Plants second trim = _/_/2025</div>",
    ].join(""),
    "gelato-33": [
      "<div class='content-item'>Clones received = _/_/2024</div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'> ___ </div>",
      "<div class='content-item'>Plants cut down and hung = _/_/2025</div>",
      "<div class='content-item'>Plants first trim = _/_/2025</div>",
      "<div class='content-item'>Plants cured = _/_/2025</div>",
      "<div class='content-item'>Plants second trim = _/_/2025</div>",
    ]
  },
  nutrients: {
    applescotti: [
      "<div style='display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px;'>",
      "<div>",
      "<h3>Vegetative Stage</h3>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='roots-gold'>House and Garden Roots Excelurator Gold</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='liquid-karma'>Botanicare Liquid Karma</div>",
      "<div class='content-item clickable' data-image='vitamino'>Botanicare Vitamino</div>",
      "<div class='content-item clickable' data-image='nitrogen-boost'>House and Garden Nitrogen Boost</div>",
      
      "</div>",
      "<div>",
      "<h3>Flower Stage</h3>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='paleo-bloom'>Primordial Solutions PaleoBloom</div>",
      "<div class='content-item clickable' data-image='true-blooms'>Primordial Solutions True Blooms</div>",
      "<div class='content-item clickable' data-image='hydroplex'>Botanicare Hydroplex</div>",
      "<div class='content-item clickable' data-image='bud-xl'>House and Garden Bud-XL</div>",
      "<div class='content-item clickable' data-image='sweet-raw'>Botanicare Sweet Raw</div>",
      "<div class='content-item clickable' data-image='sweet'>Botanicare Sweet Berry</div>",
      "<div class='content-item clickable' data-image='top-shooter'>House and Garden Top Shooter</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "</div>",
      "<div>",
      "<h3>Images</h3>",
      "<div class='content-item clickable' data-image='Img_1'>Img_1</div>",
      "<div class='content-item clickable' data-image='Img_2'>Img_2</div>",
      "<div class='content-item clickable' data-image='Img_3'>Img_3</div>",
      "<div class='content-item clickable' data-image='Img_4'>Img_4</div>",
      "<div class='content-item clickable' data-image='Img_5'>Img_5</div>",
      "<div class='content-item clickable' data-image='Img_6'>Img_6</div>",
      "<div class='content-item clickable' data-image='Img_7'>Img_7</div>",
      "<div class='content-item clickable' data-image='Img_8'>Img_8</div>",
      "<div class='content-item'><a href='#' onclick='window.open(\"https://bellatoka.app/under-construction\", \"_blank\")'>Full Schedule</a></div>",
      "</div>",
      "</div>",
    ].join(""),
    "gelato-33": [
      "<div style='display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px;'>",
      "<div>",
      "<h3>Vegetative Stage</h3>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Coco A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Coco B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='roots-gold'>House and Garden Roots Excelurator Gold</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "<div class='content-item clickable' data-image='liquid-karma'>Botanicare Liquid Karma</div>",
      "<div class='content-item clickable' data-image='vitamino'>Botanicare Vitamino</div>",
      "<div class='content-item clickable' data-image='nitrogen-boost'>House and Garden Nitrogen Boost</div>",
      "</div>",
      "<div>",
      "<h3>Flower Stage</h3>",
      "<div class='content-item clickable' data-image='power-si'>Power SI Potassium Silicate</div>",
      "<div class='content-item clickable' data-image='cocos-a'>House and Garden Cocos A</div>",
      "<div class='content-item clickable' data-image='cocos-b'>House and Garden Cocos B</div>",
      "<div class='content-item clickable' data-image='cal-mag'>Botanicare Cal-Mag Plus</div>",
      "<div class='content-item clickable' data-image='diamond-nectar'>General Hydroponics Diamond Nectar</div>",
      "<div class='content-item clickable' data-image='hydroguard'>Botanicare Hydroguard</div>",
      "<div class='content-item clickable' data-image='paleo-bloom'>Primordial Solutions PaleoBloom</div>",
      "<div class='content-item clickable' data-image='true-blooms'>Primordial Solutions True Blooms</div>",
      "<div class='content-item clickable' data-image='hydroplex'>Botanicare Hydroplex</div>",
      "<div class='content-item clickable' data-image='bud-xl'>House and Garden Bud-XL</div>",
      "<div class='content-item clickable' data-image='sweet-raw'>Botanicare Sweet Raw</div>",
      "<div class='content-item clickable' data-image='sweet'>Botanicare Sweet Berry</div>",
      "<div class='content-item clickable' data-image='top-shooter'>House and Garden Top Shooter</div>",
      "<div class='content-item clickable' data-image='sea-green'>Primordial Solutions Sea Green</div>",
      "</div>",
      "<div>",
      "<h3>Images</h3>",
      "<div class='content-item clickable' data-image='Img_1'>Img_1</div>",
      "<div class='content-item clickable' data-image='Img_2'>Img_2</div>",
      "<div class='content-item clickable' data-image='Img_3'>Img_3</div>",
      "<div class='content-item clickable' data-image='Img_4'>Img_4</div>",
      "<div class='content-item clickable' data-image='Img_5'>Img_5</div>",
      "<div class='content-item clickable' data-image='Img_6'>Img_6</div>",
      "<div class='content-item clickable' data-image='Img_7'>Img_7</div>",
      "<div class='content-item clickable' data-image='Img_8'>Img_8</div>",
      "<div class='content-item'><a href='#' onclick='window.open(\"https://bellatoka.app/under-construction\", \"_blank\")'>Full Schedule</a></div>",
      "</div>",
      "</div>",
    ].join(""),
  },
  "pest-management": {
    applescotti: [
      "<div class='content-item clickable' data-image='<needed>'>Neem Oil<a>  </a></a><a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='<needed>'>Regalia CG Biofungicide<a>  </a></a><a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='<needed>'>Molt-X<a>  </a></a><a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      "<div class='content-item clickable' data-image='<needed>'>The Amazing Doctor Zymes<a>  </a></a><a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Link</a></div>",
      
      "<div class='content-item'><a href='#' onclick='window.open(\"bellatoka.app/pesticide-list\", \"_blank\")'>Full List of Legal Pesticides for Indoor Cannabis Cultivation</a></div>",
    ].join(""),
    "gelato-33": [
      "<div class='content-item'>Start = 6/3</div>",
      "<div class='content-item'>molt x = 6/15</div>",
      "<div class='content-item'>molt x = 6/15</div>",
      "<div class='content-item'>molt x = 6/15</div>",
      "<div class='content-item'>molt x = 6/15</div>",
      "<div class='content-item'><a href='/pesticide-list' target='_self'>Regalia = 7/2</a></div>",
      "<div class='content-item'><a href='#' onclick='window.open(\"https://google.com\", \"_blank\")'>Harvest = 9/11</a></div>",
    ].join(""),
  },
};
